In [1]:
import gdown
import pandas as pd

gdown.download(r'https://bit.ly/3736JW1', 'ns_book6.csv', quiet=False)
ns_book6 = pd.read_csv('ns_book6.csv', low_memory=False)
ns_book6.head()
ns_book6.astype({'발행년도':'int64'})

Downloading...
From: https://bit.ly/3736JW1
To: c:\data\ns_book6.csv
100%|██████████| 55.0M/55.0M [00:06<00:00, 8.61MB/s]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
379971,401674,소설의 사회사 비교론,조동일 지음,지식산업사,2001,9788942340262,9788942300365,NaN,3,809.3,1,0,1970-01-01
379972,401677,큰오빠,박정근 지음,우리문학사,1998,9788974231323,9788974231309,NaN,2,813.6,2,0,1970-01-01
379973,401678,韓國現代詩大系,채만묵 編著,한국문화사,1996,9788977352971,9788977352988,NaN,3,811.608,1,0,1970-01-01
379974,401679,뉴 웨이브,제임스 모나코 지음,한나래,1996,9788985367448,9788985367424,NaN,2,688.04,1,0,1970-01-01
379975,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,1995,9788947700368,9788947700405,NaN,3,809.05,2,0,1970-01-01

In [2]:
ns_book6.head()
ns_book6.astype({'발행년도':'int64'})

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
379971,401674,소설의 사회사 비교론,조동일 지음,지식산업사,2001,9788942340262,9788942300365,NaN,3,809.3,1,0,1970-01-01
379972,401677,큰오빠,박정근 지음,우리문학사,1998,9788974231323,9788974231309,NaN,2,813.6,2,0,1970-01-01
379973,401678,韓國現代詩大系,채만묵 編著,한국문화사,1996,9788977352971,9788977352988,NaN,3,811.608,1,0,1970-01-01
379974,401679,뉴 웨이브,제임스 모나코 지음,한나래,1996,9788985367448,9788985367424,NaN,2,688.04,1,0,1970-01-01
379975,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,1995,9788947700368,9788947700405,NaN,3,809.05,2,0,1970-01-01

In [3]:
# 기술통계로 요약하기
import numpy as np
ns_book6.describe()

ns_book7 = ns_book6[ns_book6['도서권수'] > 0]

ns_book7.describe(percentiles=[0.3, 0.6, 0.9])
ns_book7.describe(include='object')
ns_book7.columns

ns_book7['대출건수'].mean() #11
ns_book7['대출건수'].median()#6

pd.Series([1, 2, 3, 4, 5]).quantile(0.9, interpolation='nearest')

borrow_10_flag = ns_book7['대출건수'] < 10
borrow_10_flag.mean()

ns_book7['대출건수'].quantile(0.65)

differ = ns_book7['대출건수'] - ns_book7['대출건수'].mean()
np.sqrt(np.sum(differ**2) / (differ.count()-1))

ns_book7.describe(include='object')

ns_book7 = ns_book7.astype({'발행년도':'int32'})
ns_book7['발행년도'].mode()

0    2012
Name: 발행년도, dtype: int32

In [4]:
import numpy as np



values, counts = np.unique(ns_book7['도서명'], return_counts=True)
idx_counts = np.argsort(-counts)
top_values = values[idx_counts]
top_counts = counts[idx_counts]

book_zip = zip(top_values[:10], top_counts[:10])

for values, counts in book_zip:
    print(values, int(counts))
    
    
a = [1, 10, 3, 6, 20]
df = pd.Series(a)

print(df.var(), df.std())

승정원일기 250
일성록 168
(影印標點) 韓國文集叢刊 續 117
三國志 102
(影印標點)韓國文集叢刊 78
애거서 크리스티 전집 77
한국 고전소설사 큰 사전 72
세상에 대하여 우리가 더 잘 알아야 할 교양 61
전략 삼국지 60
(전략)삼국지 60
56.5 7.516648189186454

In [ ]:
#평균 대출건수가 가장 높은 10개 출판사 추출 명령어
loan_df = ns_book7.groupby(by=['출판사'], dropna=False)['대출건수'] \
        .mean() \
        .sort_values(ascending=False) \
        .to_frame('평균대출건수')
loan_df['순위'] = range(1, len(loan_df)+1)
loan_df = loan_df.reset_index().set_index('순위')
loan_df.head(10)

                출판사      평균대출건수
순위
1             동녁라이프  224.000000
2            와이비엠시사  215.000000
3                환상  210.000000
4   두앤비컨텐츠(랜덤하우스중앙)  167.000000
5      개미들출판사-에셀문화사  157.000000
6        해커스 어학 연구소  149.500000
7       Test clinic  137.000000
8             마야출판사  133.333333
9          해밀 & Co.  133.000000
10       마그나(Magna)  130.000000

In [39]:
#대출건수 25% ~ 75% 범위 내의 도서가 전체 도서 중 차지하는 비중
q1, q3 = ns_book7['대출건수'].quantile([0.25, 0.75])
q_array = (ns_book7['대출건수'] >= q1) & (ns_book7['대출건수'] <= q3)
q_rate = (q_array.sum() / len(ns_book7)) * 100

q_rate

np.float64(51.51737134060568)